"""A portable SVG of the exact flat Magic geometry, never a schematic mock-up."""

from html import escape

from .magic import GRID, bounds, rectangles


def render_svg(directory, metadata):
    shapes = rectangles(directory / "layout.mag")
    x0, y0, x1, y1 = bounds(shapes)
    width, height = x1 - x0, y1 - y0
    margin = max(width * 0.025, 300)
    palette = {
        "pwell": "#b384af",
        "nwell": "#88bdb1",
        "ndiff": "#83a757",
        "pdiff": "#dfbf63",
        "nmos": "#d76464",
        "pmos": "#d76464",
        "poly": "#da7372",
        "npolyres": "#da7372",
        "locali": "#bba49a",
        "metal1": "#8fa8d6",
        "metal2": "#bc9aca",
        "metal3": "#58a1cb",
        "metal4": "#d8bd73",
        "mimcap": "#73bcbc",
        "mimcapcontact": "#98dede",
        "via": "#eff5ff",
        "via2": "#eff5ff",
        "via3": "#eff5ff",
        "viali": "#c4d4d9",
        "polycont": "#e4a0a0",
        "ndiffc": "#c5d49e",
        "pdiffc": "#e9d3a7",
        "psubdiffcont": "#82a897",
        "nsubdiffcont": "#af99c0",
    }
    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width + 2 * margin} {height + 4 * margin}" role="img">',
        "<title>SKY130 physical layout generated by ChipJev and checked in Magic</title>",
        '<rect width="100%" height="100%" fill="#071a31"/>',
        f'<g transform="translate({margin - x0},{height + 2 * margin + y0}) scale(1,-1)">',
    ]
    for layer, color in palette.items():
        lines.append(f'<g fill="{color}" opacity="{0.18 if "well" in layer else 0.8}">')
        for a, b, c, d in shapes.get(layer, []):
            lines.append(f'<rect x="{a}" y="{b}" width="{c - a}" height="{d - b}"/>')
        lines.append("</g>")
    lines.append("</g>")
    font = max(width / 110, 110)
    label = f"{metadata['topology']}   |   {width * GRID:.1f} × {height * GRID:.1f} µm"
    lines.append(
        f'<text x="{margin}" y="{margin}" fill="#d5e7f7" '
        f'font-family="monospace" font-size="{font}">{escape(label)}</text>'
    )
    lines.append(
        f'<text x="{margin}" y="{height + 3.25 * margin}" fill="#a8c1d7" '
        f'font-family="sans-serif" font-size="{font}">'
        "PDK wells, devices and contacts · M1 access · M2 branches · M3 nets</text>"
    )
    lines.append("</svg>")
    (directory / "layout.svg").write_text("\n".join(lines))
